"""
报告生成器
生成药物研发全流程报告
"""

import json
import logging
from datetime import datetime
from typing import Optional

from openai import OpenAI

logger = logging.getLogger(__name__)


class Reporter:
    """药物研发报告生成器"""

    def __init__(self, llm_client: Optional[OpenAI] = None, llm_model: str = "mimo-v2-pro"):
        self.llm = llm_client
        self.model = llm_model

    def generate_pipeline_report(
        self,
        pipeline_result: dict,
        format: str = "markdown"
    ) -> str:
        """
        生成Pipeline全流程报告

        Args:
            pipeline_result: Pipeline执行结果
            format: 输出格式 (markdown/json/html)
        """
        if format == "json":
            return json.dumps(pipeline_result, indent=2, ensure_ascii=False, default=str)

        # Markdown报告
        report = self._build_markdown_report(pipeline_result)

        if self.llm:
            try:
                enhanced = self._enhance_with_llm(report, pipeline_result)
                return enhanced
            except Exception as e:
                logger.warning(f"LLM报告增强失败: {e}")

        return report

    def _build_markdown_report(self, data: dict) -> str:
        """构建Markdown报告"""
        disease = data.get("disease", "Unknown")
        target = data.get("target", "Unknown")
        stages = data.get("stages_completed", [])
        candidates = data.get("final_candidates", [])
        elapsed = data.get("execution_time", 0)

        report = f"""# 💊 MediPharma 药物发现报告

> 疾病: {disease} | 靶点: {target} | 时间: {data.get('timestamp', '')[:10]}

## 📊 执行概况

| 指标 | 数值 |
|------|------|
| 完成阶段 | {len(stages)} |
| 最终候选 | {len(candidates)} |
| 执行耗时 | {elapsed:.1f}s |
| 流程阶段 | {' → '.join(stages)} |

"""

        # 靶点发现结果
        if data.get("target_report"):
            tr = data["target_report"]
            report += f"""## 🎯 靶点发现

- 分析疾病: {tr.get('disease', '')}
- 候选靶点总数: {tr.get('total_candidates', 0)}
- Top靶点:

| 排名 | 基因 | 综合分 | 推荐 |
|------|------|--------|------|
"""
            for t in tr.get("top_targets", [])[:5]:
                report += f"| {t.get('rank', '-')} | {t.get('gene_symbol', '')} | {t.get('total_score', 0):.3f} | {t.get('recommendation', '')} |\n"

        # 虚拟筛选结果
        if data.get("screening_report"):
            sr = data["screening_report"]
            report += f"""
## 🔬 虚拟筛选

- 筛选化合物: {sr.get('total_screened', 0)}
- 发现Hit: {sr.get('hits_found', 0)}
- 筛选方法: {sr.get('method', '')}
"""

        # 分子生成结果
        if data.get("generation_report"):
            gr = data["generation_report"]
            report += f"""
## 🧬 分子生成

- 生成总数: {gr.get('total_generated', 0)}
- 有效分子: {gr.get('valid_molecules', 0)}
- 生成方法: {gr.get('method', '')}
"""

        # 最终候选
        if candidates:
            report += "\n## 🏆 最终候选化合物\n\n"
            report += "| 排名 | SMILES | 综合分 | 备注 |\n|------|--------|--------|------|\n"
            for i, c in enumerate(candidates[:10]):
                smiles = c.get("smiles", "")[:40]
                score = c.get("composite_score", c.get("confidence", 0))
                report += f"| {i+1} | `{smiles}...` | {score:.3f} | - |\n"

        # 结论
        report += f"""
## 📋 结论

本报告由MediPharma AI平台自动生成。
基于红杉"伪装成服务公司的软件公司"理念——我们交付候选化合物结果，而非工具。

---
*Generated by MediPharma v2.0 | {datetime.now().strftime('%Y-%m-%d %H:%M')}*
"""
        return report

    def _enhance_with_llm(self, report: str, data: dict) -> str:
        """使用LLM增强报告质量"""
        resp = self.llm.chat.completions.create(
            model=self.model,
            messages=[
                {
                    "role": "system",
                    "content": "你是药物研发报告写作专家。优化以下报告的语言和结构，保持所有数据不变，使叙述更专业、更流畅。保留所有表格和数据。"
                },
                {
                    "role": "user",
                    "content": report[:3000]
                }
            ],
            temperature=0.3
        )
        return resp.choices[0].message.content
